export const INSTRUCTOR_COURSE_REQUEST = "INSTRUCTOR_COURSE_REQUEST";
export const INSTRUCTOR_COURSE_SUCCESS = "INSTRUCTOR_COURSE_SUCCESS";
export const INSTRUCTOR_COURSE_FAIL = "INSTRUCTOR_COURSE_FAIL";

export const ALL_COURSE_REQUEST = "ALL_COURSE_REQUEST";
export const ALL_COURSE_SUCCESS = "ALL_COURSE_SUCCESS";
export const ALL_COURSE_FAIL = "ALL_COURSE_FAIL";

export const USER_COURSE_REQUEST = "USER_COURSE_REQUEST";
export const USER_COURSE_SUCCESS = "USER_COURSE_SUCCESS";
export const USER_COURSE_FAIL = "USER_COURSE_FAIL";

export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST";
export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS";
export const COURSE_DETAILS_FAIL = "COURSE_DETAILS_FAIL";

export const CHECK_ENROLL_REQUEST = "CHECK_ENROLL_REQUEST";
export const CHECK_ENROLL_SUCCESS = "CHECK_ENROLL_SUCCESS";
export const CHECK_ENROLL_FAIL = "CHECK_ENROLL_FAIL";

export const LESSONE_COMPLETE_REQUEST = "LESSONE_COMPLETE_REQUEST";
export const LESSONE_COMPLETE_SUCCESS = "LESSONE_COMPLETE_SUCCESS";
export const LESSONE_COMPLETE_FAIL = "LESSONE_COMPLETE_FAIL";

export const MARK_COMPLETE_REQUEST = "MARK_COMPLETE_REQUEST";
export const MARK_COMPLETE_SUCCESS = "MARK_COMPLETE_SUCCESS";
export const MARK_COMPLETE_FAIL = "MARK_COMPLETE_FAIL";
export const MARK_COMPLETE_RESET = "MARK_COMPLETE_RESET";

export const MARK_INCOMPLETE_REQUEST = "MARK_INCOMPLETE_REQUEST";
export const MARK_INCOMPLETE_SUCCESS = "MARK_INCOMPLETE_SUCCESS";
export const MARK_INCOMPLETE_FAIL = "MARK_INCOMPLETE_FAIL";
export const MARK_INCOMPLETE_RESET = "MARK_INCOMPLETE_RESET";

export const NEW_COURSE_REQUEST = "NEW_COURSE_REQUEST";
export const NEW_COURSE_SUCCESS = "NEW_COURSE_SUCCESS";
export const NEW_COURSE_RESET = "NEW_COURSE_RESET";
export const NEW_COURSE_FAIL = "NEW_COURSE_FAIL";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_RESET = "DELETE_COURSE_RESET";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_RESET = "UPDATE_COURSE_RESET";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";

export const FREE_ENROLLMENT_REQUEST = "FREE_ENROLLMENT_REQUEST";
export const FREE_ENROLLMENT_SUCCESS = "FREE_ENROLLMENT_SUCCESS";
export const FREE_ENROLLMENT_FAIL = "FREE_ENROLLMENT_FAIL";

export const PAID_ENROLLMENT_REQUEST = "PAID_ENROLLMENT_REQUEST";
export const PAID_ENROLLMENT_SUCCESS = "PAID_ENROLLMENT_SUCCESS";
export const PAID_ENROLLMENT_FAIL = "PAID_ENROLLMENT_FAIL";

export const PRODUCT_COURSE_REQUEST = "PRODUCT_COURSE_REQUEST";
export const PRODUCT_COURSE_SUCCESS = "PRODUCT_COURSE_SUCCESS";
export const PRODUCT_COURSE_FAIL = "PRODUCT_COURSE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
