export const ENROLLED_STUDENT_REQUEST = "ENROLLED_STUDENT_REQUEST";
export const ENROLLED_STUDENT_SUCCESS = "ENROLLED_STUDENT_SUCCESS";
export const ENROLLED_STUDENT_FAIL = "ENROLLED_STUDENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
